# Generated by Django 3.2.9 on 2022-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
