# Generated by Django 4.0.2 on 2022-02-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_navbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image_url',
            new_name='img_urls',
        ),
    ]
