# Generated by Django 4.0.2 on 2022-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_url',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
